# Generated by Django 3.0.2 on 2020-02-22 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0005_auto_20200222_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 22, 10, 20, 24, 357034, tzinfo=utc)),
        ),
    ]
